// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO5Da77TunXEuh-dEdjKLHL3H3Kbr7hTY',
    appId: '1:766389898218:web:6bed01c87fdeaa1f7d8093',
    messagingSenderId: '766389898218',
    projectId: 'brokecheck-d0f86',
    authDomain: 'brokecheck-d0f86.firebaseapp.com',
    storageBucket: 'brokecheck-d0f86.firebasestorage.app',
    measurementId: 'G-1QW39DG8TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWvOjw-11dgH3Ey-AXVI8Jw9zWYB5eYnc',
    appId: '1:766389898218:android:887e1e7c07d8d97b7d8093',
    messagingSenderId: '766389898218',
    projectId: 'brokecheck-d0f86',
    storageBucket: 'brokecheck-d0f86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1VeVC2koSbF0qkUXk03lPaYkDNOxWr0M',
    appId: '1:766389898218:ios:b4c2fd893d5a97147d8093',
    messagingSenderId: '766389898218',
    projectId: 'brokecheck-d0f86',
    storageBucket: 'brokecheck-d0f86.firebasestorage.app',
    iosBundleId: 'com.example.brokecheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1VeVC2koSbF0qkUXk03lPaYkDNOxWr0M',
    appId: '1:766389898218:ios:b4c2fd893d5a97147d8093',
    messagingSenderId: '766389898218',
    projectId: 'brokecheck-d0f86',
    storageBucket: 'brokecheck-d0f86.firebasestorage.app',
    iosBundleId: 'com.example.brokecheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO5Da77TunXEuh-dEdjKLHL3H3Kbr7hTY',
    appId: '1:766389898218:web:356831a14adeb2667d8093',
    messagingSenderId: '766389898218',
    projectId: 'brokecheck-d0f86',
    authDomain: 'brokecheck-d0f86.firebaseapp.com',
    storageBucket: 'brokecheck-d0f86.firebasestorage.app',
    measurementId: 'G-LYWSB3VVNW',
  );
}
